/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import CheckingDialogUI from "./script/CheckingDialogUI"
import GameUI from "./script/GameUI"
import StartUI from "./script/StartUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="checkingDialog.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/CheckingDialogUI.ts",CheckingDialogUI);
        reg("script/GameUI.ts",GameUI);
        reg("script/StartUI.ts",StartUI);
    }
}
GameConfig.init();